services:
  mysql:
    image: mysql:8.4
    container_name: incident-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: incident_management
    ports:
      - "3306:3306"
    volumes:
      - incident_mysql_data:/var/lib/mysql

volumes:
  incident_mysql_data:
